# Generated by Django 3.2.4 on 2021-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_document_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
    ]
